// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXB-6YfNqnsaCba-fQyhsrebMBq80__UQ',
    appId: '1:69187769094:web:b7b873131bb81488d6c487',
    messagingSenderId: '69187769094',
    projectId: 'notes-39cae',
    authDomain: 'notes-39cae.firebaseapp.com',
    storageBucket: 'notes-39cae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-LUqLRtfZh-n9Dlbt9BQI4Kb8LBP8_A',
    appId: '1:69187769094:android:5d963ee5d841f2ffd6c487',
    messagingSenderId: '69187769094',
    projectId: 'notes-39cae',
    storageBucket: 'notes-39cae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWaQUwsoIE73DbWcUSjW-BQ6Czc-76FbE',
    appId: '1:69187769094:ios:88512deec14ad4cad6c487',
    messagingSenderId: '69187769094',
    projectId: 'notes-39cae',
    storageBucket: 'notes-39cae.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWaQUwsoIE73DbWcUSjW-BQ6Czc-76FbE',
    appId: '1:69187769094:ios:ac8b7a269bd64598d6c487',
    messagingSenderId: '69187769094',
    projectId: 'notes-39cae',
    storageBucket: 'notes-39cae.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
